version: '3.8'

services:
  music-site-mssql:
    platform: linux/x86_64
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: music-site-mssql
    environment:
      SA_PASSWORD: "testtest123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "1433:1433"

volumes:
  mssql-data: