discord:
  webhook-url: ${DISCORD_URL:1234}
  username: ${DISCORD_USERNAME:1234}
  avatar-url: ${DISCORD_AVATAR:1234}
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
---
spring:
  file_upload:
    path: "${FILE_STORAGE_PATH}:/upload"